name: Build
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  build:
    if: github.base_ref == 'develop' && github.head_ref == 'main'
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Uni Test
        run: |
          npm install && npm run test
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
